export const ON_CHANGE_LIST_GROUP = "ON_CHANGE_LIST_GROUP";
export const FETCH_TODO_SUCCESS = "FETCH_TODO_SUCCESS";
export const FETCH_TODO_REQUEST = "FETCH_TODO_REQUEST";
export const ON_ADD_TODO_ITEM = "ON_ADD_TODO_ITEM";
export const ON_TODO_ITEM_DONE = "ON_TODO_ITEM_DONE";
export const ON_DELETE_TODO_ITEM = "ON_DELETE_TODO_ITEM";
export const ON_ADD_GROUP = "ON_ADD_GROUP";
